// ──────────────────────────────────────────────────────────────────
// SQL Validator Service
// Capa CRÍTICA de seguridad entre Claude y la base de datos.
// Toda consulta generada por la IA DEBE pasar por aquí antes de
// ejecutarse contra PostgreSQL.
// ──────────────────────────────────────────────────────────────────

const MAX_LIMIT = 100;

/**
 * Palabras clave SQL peligrosas (operaciones de escritura / DDL / DCL).
 * Se buscan como palabras completas (word boundaries).
 */
const BLACKLISTED_KEYWORDS = [
  'INSERT',
  'UPDATE',
  'DELETE',
  'DROP',
  'ALTER',
  'TRUNCATE',
  'CREATE',
  'GRANT',
  'REVOKE',
  'EXECUTE',
  'EXEC',
  'COPY',
  'VACUUM',
  'REINDEX',
  'COMMENT',
  'LOCK',
  'UNLOCK',
  'MERGE',
  'UPSERT',
  'REPLACE',
  'CALL',
  'SET ',
  'NOTIFY',
  'LISTEN',
  'PREPARE',
  'DEALLOCATE',
];

/**
 * Funciones de PostgreSQL potencialmente peligrosas.
 */
const DANGEROUS_FUNCTIONS = [
  'pg_sleep',
  'pg_terminate_backend',
  'pg_cancel_backend',
  'pg_reload_conf',
  'pg_rotate_logfile',
  'lo_import',
  'lo_export',
  'lo_unlink',
  'dblink',
  'dblink_exec',
  'pg_read_file',
  'pg_read_binary_file',
  'pg_ls_dir',
  'pg_stat_file',
];

/**
 * Validate a SQL query for safety.
 *
 * @param {string} rawSql - The SQL string generated by Claude.
 * @returns {{ valid: boolean, sql: string | null, error: string | null }}
 */
export function validateSQL(rawSql) {
  if (!rawSql || typeof rawSql !== 'string') {
    return { valid: false, sql: null, error: 'La consulta SQL está vacía o no es válida.' };
  }

  let sql = rawSql.trim();

  // ── Remove markdown code fences if Claude wrapped the SQL in them ──
  if (sql.startsWith('```')) {
    sql = sql.replace(/^```(?:sql)?\s*/i, '').replace(/\s*```$/, '').trim();
  }

  // ── 1. Block semicolons (prevent multi-statement injection) ────────
  if (sql.includes(';')) {
    return {
      valid: false,
      sql: null,
      error: 'La consulta contiene punto y coma (;). No se permiten múltiples sentencias.',
    };
  }

  // ── 2. Block SQL comments (prevent validation bypass) ──────────────
  if (sql.includes('--') || /\/\*[\s\S]*?\*\//.test(sql)) {
    return {
      valid: false,
      sql: null,
      error: 'La consulta contiene comentarios SQL (-- o /* */). No están permitidos.',
    };
  }

  const upperSql = sql.toUpperCase();

  // ── 3. Must start with SELECT or WITH (CTE) ───────────────────────
  if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
    return {
      valid: false,
      sql: null,
      error: 'Solo se permiten consultas SELECT (o WITH para CTEs). La consulta debe comenzar con SELECT o WITH.',
    };
  }

  // ── 4. Blacklisted keywords ────────────────────────────────────────
  for (const keyword of BLACKLISTED_KEYWORDS) {
    // Build a regex that matches the keyword as a whole word (case-insensitive)
    const regex = new RegExp(`\\b${keyword.trim()}\\b`, 'i');
    if (regex.test(sql)) {
      return {
        valid: false,
        sql: null,
        error: `La consulta contiene la palabra clave prohibida: "${keyword.trim()}". Solo se permiten consultas de lectura.`,
      };
    }
  }

  // ── 5. Dangerous functions ─────────────────────────────────────────
  for (const fn of DANGEROUS_FUNCTIONS) {
    const regex = new RegExp(`\\b${fn}\\s*\\(`, 'i');
    if (regex.test(sql)) {
      return {
        valid: false,
        sql: null,
        error: `La consulta contiene la función peligrosa: "${fn}". No está permitida.`,
      };
    }
  }

  // ── 6. Ensure LIMIT exists and is ≤ MAX_LIMIT ─────────────────────
  const limitMatch = upperSql.match(/\bLIMIT\s+(\d+)\s*$/);

  if (limitMatch) {
    const currentLimit = parseInt(limitMatch[1], 10);
    if (currentLimit > MAX_LIMIT) {
      // Replace the limit with MAX_LIMIT
      sql = sql.replace(/\bLIMIT\s+\d+\s*$/i, `LIMIT ${MAX_LIMIT}`);
    }
  } else {
    // No LIMIT found — append one
    sql = `${sql} LIMIT ${MAX_LIMIT}`;
  }

  return { valid: true, sql, error: null };
}
